all:
	ocamlc -c \
 safelist.mli \
 safelist.ml \
 uprintf.mli \
 uprintf.ml \
 util.mli \
 util.ml \
 uarg.mli \
 uarg.ml \
 prefs.mli \
 prefs.ml \
 trace.mli \
 trace.ml \
 rx.mli \
 rx.ml \
 myMap.mli \
 myMap.ml \
