OCAMLC = -I ../ubase/

all:
	ocamllex src2fcl.mll 
	ocamlc -c src2fcl.mli src2fcl.ml 
	ocamlc $(OCAMLC) -c \
   error.mli \
   error.ml \
 baker.ml \
 misc.mli \
 misc.ml \
 mapplus.mli \
 mapplus.ml \
 int.mli \
 int.ml \
 info.mli \
 info.ml \
 env.mli \
 env.ml \
 name.mli \
 name.ml \
 memo.mli \
 memo.ml \
